title="Identifiers.org SPARQL"

[[tabGroups]]

name="Example Queries"

[[tabGroups.tabs]]

name="Oldest namespaces (by registration date)"
query="""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX : <http://identifiers.org/>

SELECT ?name ?created { 
	?i a :Namespace . 
	?i rdfs:label ?name ;
       dcterms:created ?created .
}
ORDER BY ?created
LIMIT 20
"""

[[tabGroups.tabs]]

name="Number of resources per institution"
query="""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://identifiers.org/>

SELECT ?institution_name (COUNT(?resource) as ?num_resources) { 
	?institution a :Institution ; 
                 rdfs:label ?institution_name ; 
                 :responsibleFor ?resource .
}
GROUP BY ?institution_name
ORDER BY DESC(?num_resources)
LIMIT 20
"""



